### ISSUE TITLE
metalsmith-in-place@4.4.1 requires pug@^2.0.0-rc.4 via jstransformer-pug@0.3.0

### ISSUE THREAD

**Issue by jwhaney** [jstransformers/jstransformer-pug#12]
Hello, I was wondering if this is something that @jstransformers is planning to address? I see there is a PR #11 but looks like some CI checks failed. The title of this issue is specific to my project. There may be other packages I can use to get around my specific problem, but just wanted to check here first. Any help/information is greatly appreciated.

**Comment by RobLoach** [comment]
Thanks! This should be good now.
